version: '{build}'

image: 'Visual Studio 2017'

skip_commits:
  message: /\[skip ci\]/

environment:
  APPVEYOR_NUGET_API_KEY:
    secure: mpAaxyuSuuvCUyaZtUMQyADQ1z3IV7GAR20OQ2poqAQtyvjiOKR0OaiEPKF5bRUr
  APPVEYOR_GITHUB_USERNAME: 'EsOsO'
  APPVEYOR_GITHUB_EMAIL:
    secure: qOw7foLVABiwY5Y4Th58VNI8sbyJpNwvkFSI9DFxqII=

build: false

test_script:
  - ps: . .\build.ps1

deploy:
  tag: $(ReleaseVersion)
  description: $(ReleaseDescription)
  force_update: true
  draft: false
  prerelease: false
  provider: GitHub
  auth_token:
    secure: +qE3B06ZU3qbWDRZLAU+gIqJBnlWBGl8Uk7177ARCb2n5MAWe+P2wNUjPx7SoJEo
