
jobs:
  - job: Build module
    pool:
      vmImage: vs2017-win2016
    steps:
    - powershell: ./build.ps1 -Task Build -Verbose
      displayName: 'Build Module Artifact'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifact'
      inputs:
        pathtoPublish: $(System.DefaultWorkingDirectory)
        artifactName: Module
  - job: Test
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: none #skip checking out the default repository resource
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: Module
        downloadPath: $(System.DefaultWorkingDirectory)
    dependsOn: Build
    condition: succeeded()
