jobs:
  - job: build_powershell_win2016
    displayName: "Powershell v5.x - Windows 2016"
    pool:
      vmImage: vs2017-win2016
    steps:
    - powershell: ./build.ps1 -Task Test -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/Tests/TestResults.xml'
        testRunTitle: 'PS_Win2016'
      displayName: 'Publish Test Results'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '**/Tests/CodeCoverage.xml'
