site_name: SuperAwesomeModule Documentation
site_description: Super Awesome Module
site_author: Massimo Bonvicini
repo_url: https://github.com/EsOsO/SuperAwesomeModule
edit_uri: edit/master/docs/
copyright: "SuperAwesomeModule is licensed under the <a href='https://github.com/EsOsO/SuperAwesomeModule/blob/master/docs/LICENSE.md'>MIT license</a>"
theme: readthedocs
nav:
  - Home: index.md
  - Usage: usage.md
  - About:
    - Changelog: CHANGELOG.md
    - Contributing: CONTRIBUTING.md
    - License: LICENSE.md
  - Functions:
