name: Tests
on: [push]
jobs:
  pwsh_tests:
    name: Module tests on ${{ matrix.os }} - ${{ matrix.powershell }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macOS-latest
            shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Pester tests
        shell: pwsh
        run: ./build.ps1 -Task Test
