name: Workflow
on: [push]
jobs:
  build:
    name: Build module
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: ./build/build.ps1 -Task Package
        shell: powershell
  test:
    name: Module tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macOS-latest
            shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Pester tests - Powershell Core
        if: matrix.shell == 'pwsh'
        shell: pwsh
        run: ./build/build.ps1 -Task Test
      - name: Run Pester tests - Windows Powershell
        if: matrix.shell == 'powershell'
        shell: powershell
        run: ./build/build.ps1 -Task Test
