name: Tests
on: [push]
jobs:
  pwsh_tests:
    name: PowerShell Core tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: PSScriptAnalyzer
        uses: devblackops/github-action-psscriptanalyzer@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PSSCRIPTANALYZER_ROOT: './Logging'
          PSSCRIPTANALYZER_SETTINGS_PATH: './.vscode/ScriptAnalyzerSettings.psd1'
      - name: Run Pester tests
        shell: pwsh
        run: ./build.ps1 -Task Test

  powershell_tests:
    name: PowerShell tests on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: PSScriptAnalyzer
        uses: devblackops/github-action-psscriptanalyzer@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PSSCRIPTANALYZER_ROOT: './Logging'
          PSSCRIPTANALYZER_SETTINGS_PATH: './.vscode/ScriptAnalyzerSettings.psd1'
      - name: Run Pester tests
        shell: powershell
        run: .\build.ps1 -Task Test
